In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import make_classification

In [4]:
X,y=make_classification(n_samples=1000,n_classes=2,n_features=10,n_clusters_per_class=1,random_state=42)

In [5]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    1.376053 -1.607661 -0.835143 -0.319848 -0.936875  1.603393  0.568754   
1   -0.005795  1.671348 -0.176134 -0.893746  1.616256 -1.371212 -0.000382   
2    2.023848  0.082773  1.959837 -0.482314  0.145563  1.068923  0.838405   
3    1.325083 -0.985804  0.692856 -0.179093 -0.976913  1.607253  0.547594   
4    0.872125 -0.550587  1.302590 -1.137033  1.115297 -0.430140  0.362603   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.119733 -2.850030 -1.206022 -1.000629  2.573573 -2.837510 -0.460550   
996  0.851714  0.295280 -2.371659  0.994447 -1.001866  1.349541  0.351506   
997  2.726151  0.210601 -0.080917  0.026205 -0.128792  1.714781  1.128937   
998  0.071282  0.603248  0.228996  0.441307 -1.561898  1.363784  0.027573   
999  1.661884 -0.630458  0.091315 -0.041248  0.207896  0.802964  0.688567   

            7         8         9  
0    0.151758  0.184741  2.089539  
1   -0.387965 -0.901376 -2.899514  
2    1.098983  0.036783  0.450613  
3    0.395820 -0.284155  0.734638  
4   -0.821815  0.509689  0.137662  
..        ...       ...       ...  
995 -0.855095  0.544582 -0.885971  
996  0.646006 -0.776499  2.042070  
997 -0.303564 -0.488476 -3.170426  
998 -0.733156  0.298158 -1.857901  
999  2.159121  1.637082 -0.380456  

[1000 rows x 10 columns]

In [6]:
y

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,

In [7]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [8]:
X_test.shape

(300, 10)

In [9]:
X_train.shape

(700, 10)

In [10]:
# Model training
from sklearn.linear_model import LogisticRegression

In [11]:
logistic=LogisticRegression()

In [12]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [13]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0
 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0
 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1
 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0
 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0
 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0
 0 1 1 1]


In [14]:
logistic.predict_proba(X_test)

array([[8.74943947e-01, 1.25056053e-01],
       [8.95983864e-01, 1.04016136e-01],
       [1.91670871e-02, 9.80832913e-01],
       [3.98248634e-03, 9.96017514e-01],
       [1.76150135e-04, 9.99823850e-01],
       [8.64543638e-01, 1.35456362e-01],
       [4.54853113e-01, 5.45146887e-01],
       [9.14478562e-01, 8.55214377e-02],
       [7.53024002e-04, 9.99246976e-01],
       [8.63866568e-01, 1.36133432e-01],
       [9.84161233e-01, 1.58387668e-02],
       [9.43496471e-01, 5.65035293e-02],
       [9.98605672e-01, 1.39432829e-03],
       [5.98150297e-01, 4.01849703e-01],
       [4.20499841e-03, 9.95795002e-01],
       [7.81231817e-01, 2.18768183e-01],
       [3.79864827e-02, 9.62013517e-01],
       [8.37230920e-01, 1.62769080e-01],
       [3.77856784e-01, 6.22143216e-01],
       [5.13023386e-01, 4.86976614e-01],
       [9.74601918e-03, 9.90253981e-01],
       [3.11751372e-01, 6.88248628e-01],
       [8.66282652e-01, 1.33717348e-01],
       [3.05522866e-01, 6.94477134e-01],
       [5.057630

In [15]:
# performance metrics
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [16]:
acc_score=accuracy_score(y_true=y_test,y_pred=y_pred)
acc_score

0.9233333333333333

In [17]:
conf_mat=confusion_matrix(y_true=y_test,y_pred=y_pred)
conf_mat

array([[146,  10],
       [ 13, 131]])

In [19]:
print(classification_report(y_true=y_test,y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93       156
           1       0.93      0.91      0.92       144

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



# Hyperparameter tuning and Cross Validation

In [47]:
logistic=LogisticRegression()

penalty=["l2"]
c_vals=[100,10,1.0,0.1,0.01]
solver=["lbfgs","liblinear","sag","saga"]

In [48]:
params=dict(penalty=penalty,C=c_vals,solver=solver)

In [49]:
from sklearn.model_selection import StratifiedKFold

cv=StratifiedKFold(n_splits=5)

In [ ]:
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=logistic,param_grid=params,scoring="accuracy",cv=cv,n_jobs=-1,error_score="raise")

In [51]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             error_score='raise', estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                         'solver': ['lbfgs', 'liblinear', 'sag', 'saga']},
             scoring='accuracy')

In [53]:
grid.best_params_

{'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}

In [54]:
grid.best_score_

np.float64(0.8985714285714286)

In [55]:
y_pred=grid.predict(X_test)
print(y_pred)

[0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0
 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0
 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1
 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0
 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0
 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0
 0 1 1 1]


# Randomized Search CV

In [58]:
from sklearn.model_selection import RandomizedSearchCV

logistic=LogisticRegression()

random=RandomizedSearchCV(estimator=logistic,param_distributions=params,scoring="accuracy",cv=5)

In [59]:
random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l2'],
                                        'solver': ['lbfgs', 'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [60]:
random.best_score_

np.float64(0.8985714285714286)

In [61]:
random.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 0.1}

In [62]:
y_pred=random.predict(X_test)
y_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1])